Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    ServiceInstanceNameRule:
      Prefix: halo
    SupplierDeployMetadata:
      ArtifactRelation:
        'centos_7_9_x64_20G_alibase_20240403.vhd':
          ArtifactId: ${Artifact.EcsImage.ArtifactId}
          ArtifactVersion: ${Artifact.EcsImage.ArtifactVersion}
    TemplateConfigs:
      - Name: 单机版
        Url: 'ros_templates/template.yaml'
        AllowedRegions:
          - cn-hangzhou
          - cn-shanghai
          - cn-beijing
          - ap-southeast-1
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: halo deploy
    Image: 'resources/icons/service_logo.png'
Artifact:
  EcsImage:
    ArtifactType: EcsImage
    ArtifactName: halo
    Description: halo
    ArtifactProperty:
      RegionId: ${ImageBuilder.EcsImage.RegionId}
      ImageId: ${ImageBuilder.EcsImage.SourceImageId}
    SupportRegionIds:
      - cn-beijing
      - cn-hangzhou
      - cn-shanghai
      - ap-southeast-1
ImageBuilder:
  EcsImage:
    RegionId: ap-southeast-1
    SourceImageId: centos_7_9_x64_20G_alibase_20240403.vhd
    InstanceType: ecs.c6.large
    InternetMaxBandwidthOut: 5
    CommandType: RunShellScript
    Timeout: 10800
    Tags: [ ]
    CommandContent: |-
      #!/bin/bash
      yum-config-manager --add-repo http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
      yum makecache fast
      yum install -y git
      yum -y install docker-ce jq
      systemctl enable docker
      systemctl start docker

      mkdir -p /home/admin/application

      cd /root/
      git clone https://github.com/aliyun-computenest/quickstart-halo
      cd quickstart-halo

      cat > /etc/systemd/system/halo.service <<EOF
      [Unit]
      Description=Halo Application Service
      Requires=docker.service
      After=docker.service

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      WorkingDirectory=/root/quickstart-halo
      ExecStart=/usr/bin/docker compose up -d
      ExecStop=/usr/bin/docker compose down
      TimeoutStartSec=0

      [Install]
      WantedBy=multi-user.target
      EOF